docker-files metadata
demisto/dockerfiles-info pull request #5
Opened 2023-08-02 10:19 UTC by GuyAfik

2023-08-02 10:29 UTC, JudahSchwartz commented
lets merge this in the same pr as the update script change

2023-08-02 13:41 UTC, kobymeir requested changes

2023-08-02 13:41 UTC, kobymeir commented on dockerfiles-metadata.json
> +    "docker_images":{
@GuyAfik can we add a scheme to this file, explaining the fields? consult with @kgal-pan about it. he did something for pack_metadata.json.

2023-08-02 13:41 UTC, kobymeir commented on dockerfiles-metadata.json
> +             "python_version":""
why it's empty here? if it's not applicable for this image or python doesn't exist, maybe we can skip empty keys creation?

2023-08-02 13:41 UTC, kobymeir commented on dockerfiles-metadata.json
> +             "python_version":""
it's also empty here? and in some other places, why?

2023-08-02 19:25 UTC, kgal-pan commented on dockerfiles-metadata.json
> +    "docker_images":{
https://github.com/demisto/content/pull/21405

2023-08-09 11:45 UTC, GuyAfik commented
will implement it in the same PR along with schema @kobymeir @JudahSchwartz , closing it

2023-08-09 11:45 UTC, closed without merging